### ISSUE TITLE
non-compliant NFTs

### ISSUE THREAD

**Issue by ghost** [near-apps/uhhm-market#1]
Your NFTs are non-compliant. This hurts the ecosystem as users will be confused why your NFTs don't work everywhere when they should.

I've already reached out on Telegram NEAR NFT Standardisation Working Group to @mattlockyer with no reply. 

<img width="1486" alt="Screenshot 2021-08-30 at 14 00 21" src="https://user-images.githubusercontent.com/4870868/131343014-dc4e7bb5-ed4a-4585-b54f-283ee9f8af11.png">

According to [NEP-199](https://github.com/near/NEPs/blob/master/specs/Standards/NonFungibleToken/Payout.md) [your implementation](https://github.com/zavodil/pluminite-ui/blob/master/contract/src/nft_core.rs#L195) is non-compliant.

[Other marketplaces](https://github.com/zavodil/pluminite-ui/blob/master/contract/src/nft_core.rs#L195) have based their implementation on yours producing an ecosystem of non-compliant NFT ecosystems.

You're not following your own standards. 

This hurts the whole ecosystem. NEAR becomes known to end-users as a platform where NFTs are not really NFT's contrary to common knowledge. To developers NEAR becomes known as a place with no standards, where they don't follow standards they set themselves. All users alike will jump ship to the next platform that provides a consistent experience. 

The reason why projects like OpenSea are so successful is because of standards. NFTs flow in and out, it doesn't matter where they came from. An NFT is an NFT that can do things that everybody expects an NFT to do. At least everyone gets that idea when they use OpenSea.

Many people are just starting to learn about NFTs for the first time and confusing non-consistent experiences are just going to be bad for everybody especially NEAR.

If we want adoption and long-term growth, we need to get 1 thing right - STANDARDS and lead by action not by empty words. As Rust dev who has worked with many tools in the Rust ecosystem, I've learnt that standards and common agreed practices which partly, are enforced by the compiler, is what makes Rust so great. I think no Rust developer would want to work on NEAR when they realise you use Rust to build dynamically untyped idiosyncratic ecosystems.

**Comment by mattlockyer** [comment]
I was on vacation and have answered you in Telegram group. Before you run around pointing fingers at this particular repo, you may want to ask questions and gather the historical context around why some NFTs are passing U64 vs. u64.

Context:

I wrote the standard with Mintbase and developed the [first marketplace for NFTs on NEAR](
https://github.com/near-apps/nft-market/), which Mintbase, Pluminite are closely modelled after.

**However, no one from the "official" dev platform team inside NEAR (responsible for standards) reached out to discuss their choice on the `nft_on_approve` arguments e.g. this current u64 vs. U64 issue.**

One of 2 things can happen now:

1. Dev Platform can merge this: https://github.com/near/near-sdk-rs/pull/552 and also update their nft-transfer method. AND update the nomicon.

2. Everyone who's already deployed NFTs and marketplaces can update all of their contracts (unlikely). This would require a redeploy of hundreds of Mintbase stores and several other applications.
